# Generated by Django 4.1.7 on 2023-05-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('quantity_of_sold', models.IntegerField(verbose_name='Кількість')),
                ('sold_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-arrived_date', 'name')},
        ),
        migrations.AlterField(
            model_name='product',
            name='arrived_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(verbose_name='Тер. придатності'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна закупки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Кількість'),
        ),
    ]
