# Generated by Django 4.1.7 on 2023-06-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapage', '0002_history_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('quantity_of_sold', models.IntegerField(verbose_name='Кількість')),
                ('sold_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
